### PR TITLE
fix opt-length when optValSize==13

### LINKED ISSUE #5: opt length encode is wrong if uri-path length == 13
## version
9a015d62da0aa9a2cdbe756ed54d11252bc7cb82

## tests

get coap://10.1.1.30/123456789abc/123456789abc   
OK

get coap://10.1.1.30/123456789abc/123456789abcd  
FAIL: malformed PDU

get coap://10.1.1.30/123456789abc/123456789abcde 
OK

## package error
image

### PR DESCRIPTION
**Pull request by yurenchen000**
fix #5 

## test

image

### CODE REVIEW

**Comment by mkovatsc** [comment]
Thanks for the PR!

It looks like the bug is also in the option delta encoding: `if (resDelta > 0){` --> `if (resDelta >= 0){`.
Would be great if you could fix this along the way... :)

`let buf = (optValSize == 13) ? new ArrayBuffer(1) : Copper.ByteUtils.convertUintToBytes(resValSize);`
This should not be needed as resValSize should be 0 when optValSize == 13. If `Copper.ByteUtils.convertUintToBytes()` does not return a buffer with 0x00, the bug is there.

Finally, it looks like the code will not produce two bytes when the nibble == 14. Could you please also fix this in the PR?

**Comment by yurenchen000** [comment]
@mkovatsc 
got it:
1. Copper.ByteUtils.convertUintToBytes(0) shoud return  `buf[0]`
2. `resDelta` has same problem with `resValSize`
3. `nibble` == 14 ? 

but there still some code & comment about `Copper.ByteUtils.convertUintToBytes(0)` make me confused
https://github.com/mkovatsc/Copper4Cr/blob/9a015d6/shared/utils/ByteUtils.js#L300
https://github.com/mkovatsc/Copper4Cr/blob/9a015d6/shared/utils/ByteUtils.js#L202

**Comment by yurenchen000** [comment]
test by compare `Copper4Cr` requrest with `coap-client`

 // opt-length nibble = 13, 14

    coap-client -m get -v9 coap://10.1.1.30/123456789abc/123456789abcd 
// opt-delta nibble = 13

    coap-client -m get -v9 coap://10.1.1.30/123456789abc/123456789abcd -O 24,0x55

// opt-delta nibble = 14

    coap-client -m get -v9 coap://10.1.1.30/123456789abc/123456789abcd -O 280,0x55

// opt-length nibble = 14

    coap-client -m get -v9 coap://10.1.1.30/123456789abc/123456789abcd -O 280,0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef

**Comment by mkovatsc** [comment]
> `Copper.ByteUtils.convertUintToBytes(0)` shoud return `buf[0]`

Sorry, I overlooked something (I have not worked CoAP in quite some time and this implementation was actually a student project). `Copper.ByteUtils.convertUintToBytes()` is most likely used for the payload. Payloads with length == 0 are represented with 0 bytes, hence it correctly returns "".

For the options we know if it should be one (nibble==13) or two (nibble==14) bytes. Just serialize the integers without the internal `Copper.ByteUtils.convertUintToBytes()`. See original Copper implementation for functionality:
```
if (delta==13) {
	byteArray.push(optDelta-13);
} else if (delta==14) {
	byteArray.push( (optDelta-269)>>>8 );
	byteArray.push( 0xFF & (optDelta-269) );
}

if (len==13) {
	byteArray.push(opt.length-13);
} else if (len==14) {
	byteArray.push( (opt.length)>>>8 );
	byteArray.push( 0xFF & (opt.length-269) );
}
```

**Comment by yurenchen000** [comment]
yes, the added function `Copper.CoapMessageSerializer.encodeOptExtend` do those thing.

**Pull request merged**
